---
- name: Install AD
  hosts: all
  gather_facts: False
 
- name: Configure Active Directory Domain Controller
  #hosts: windows_domain_controllers
  gather_facts: True
  #vars_files:
    #- [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - windows-ad-controller
  roles:
    - windows-ad-controller
